(function () {
  "use strict";

  var quizzes = {
    "your-first-week": [
      { q: "On the shared gym iPad, the Portal shows another trainer's username. What do you do?", options: ["Accept autofill, then switch clients", "Stop and use only your own approved access", "Continue if your own client book looks correct", "Change the iPad account to your personal account"], answer: 1, feedback: "Your welcome access and personal code are private. Never continue under another trainer's identity or change the shared device setup." },
      { q: "You pair JF Coach, but your assigned client list is empty. What is the safe next step?", options: ["Create the missing clients from memory", "Reinstall JF Coach and try again", "Report the empty list to management with the screen involved", "Use the Portal roster as a substitute client book"], answer: 2, feedback: "An empty or incomplete client book is a reportable access issue. Do not rebuild, guess, or use another surface as a workaround." },
      { q: "You open JF Coach and land in My Training instead of your client book. What boundary matters?", options: ["Use My Training until a client messages", "Keep trainer, client, and self-training views separate", "Add clients to My Training so they appear", "Use whichever view has the most data"], answer: 1, feedback: "Trainer, client, and My Training identities must remain separate so client data and personal training do not cross." },
      { q: "Your phone is paired correctly, but the gym iPad looks stale. What should you try first?", options: ["Reload the Portal page", "Reset the iPad account", "Reinstall every app", "Pair the iPad with your personal code"], answer: 0, feedback: "The shared iPad is pre-provisioned. Reload a stale Portal page, and do not change the device account or setup." }
    ],
    "one-on-ones-with-gabrielle": [
      { q: "A small client issue could affect tomorrow's session. What is the best use of support?", options: ["Wait until the client complains", "Book the live 1:1 early and bring the facts", "Try a private workaround first", "Save it for the quarterly review"], answer: 1, feedback: "Use support before a small issue becomes a client problem." },
      { q: "A client screen shows the wrong information. What should you bring to the 1:1?", options: ["The client name, exact screen, and issue", "A theory about the database only", "A new account you created", "A general statement that the app is broken"], answer: 0, feedback: "The exact client and screen give Gabrielle enough information to identify the next action." },
      { q: "Gabrielle has live availability in the Portal. How should you arrange the meeting?", options: ["Send a personal social message", "Ask another trainer to reserve it", "Use More, Booking Links, then the live 1:1 calendar", "Add it as a client appointment in JF Coach"], answer: 2, feedback: "Book the live 1:1 link through the Trainer Portal rather than arranging it informally." }
    ],
    "story-and-mission": [
      { q: "A nervous beginner is struggling with a complicated exercise. Which response best fits the mission?", options: ["Simplify it and help them feel capable", "Keep it because complexity proves expertise", "Compare them with an advanced client", "End the session without explanation"], answer: 0, feedback: "Jamie Fitness exists to give beginners clear structure, confidence, and a useful next action." },
      { q: "You notice a Portal workflow repeatedly confuses new clients. What should you do?", options: ["Build an unofficial process for your gym", "Raise the observation with Gabrielle or Jamie", "Tell clients to avoid the system", "Wait until a team meeting months later"], answer: 1, feedback: "Useful trainer feedback strengthens the shared system. Raise it rather than creating a private workaround." },
      { q: "You work alone at your gym and a problem is growing. Which action matches the team culture?", options: ["Keep it private so you appear independent", "Ask early through the support rhythm", "Let the client choose the solution", "Change the process without telling anyone"], answer: 1, feedback: "The role is locally independent but connected to one team through support, meetings, and escalation." }
    ],
    "how-your-role-works": [
      { q: "Your free-session calendar is full, but ongoing hours are not growing. What should you focus on?", options: ["Conversion, delivery, and retention through the full journey", "Counting every lead as an ongoing client", "Reducing support meetings", "Replacing client records with booking totals"], answer: 0, feedback: "Your role owns delivery, conversion, Strategy handoff, and retention. Ongoing hours are the success measure." },
      { q: "A free-session lead asks to move tomorrow's booking. Who should manage the change?", options: ["You in the ongoing Schedule flow", "The PT Assistant VA", "The gym manager", "The client through your personal number"], answer: 1, feedback: "The VA owns free-session and Kickstart scheduling. Trainers own ongoing-client appointments." },
      { q: "A building trainer has two weekly 1:1s. What should the sales-practice meeting use?", options: ["Only successful closes", "Real free sessions that did not convert", "Generic scripts with no client context", "Other trainers' private client messages"], answer: 1, feedback: "Real lost opportunities show the missed signal and the next line to practise." }
    ],
    "numbers-build-up-curve": [
      { q: "It is week 6, bookings are high, but few clients are ongoing. What is the best interpretation?", options: ["The build has definitely failed", "Many Kickstarts have not reached Strategy yet", "Ongoing hours no longer matter", "All new bookings should stop"], answer: 1, feedback: "The journey creates a timing lag. Keep the top of the funnel active while clients progress." },
      { q: "You have 20 early-week bookings available. How should they be placed?", options: ["Across the week at roughly 3 to 4 per day", "All on one day to simplify travel", "Only after ongoing hours appear", "In scattered isolated blocks with no daily availability"], answer: 0, feedback: "The early target is roughly 18 to 22 weekly bookings spread across the week with daily availability." },
      { q: "One KPI is weak after an unusual week. What should you do?", options: ["Treat one week as a final verdict", "Review the funnel trend and choose the weakest link", "Hide the number until it improves", "Change all stages at once"], answer: 1, feedback: "Use trends and the full funnel to choose one practical improvement." }
    ],
    "client-journey": [
      { q: "A Kickstart client finishes session three. What is the normal next stage?", options: ["Continue casual Kickstart sessions until the client asks what is next", "The Fitness Strategy Session", "Ask the VA to choose an ongoing package", "Move straight into recurring appointments without a handoff"], answer: 1, feedback: "The Fitness Strategy Session is the handoff from Kickstart to an ongoing prescription." },
      { q: "A Savings client reaches week 12 and asks whether training ends. What do you explain?", options: ["The package expires immediately", "The minimum is complete and the arrangement moves naturally to Flexi", "They need another free session", "Their unused sessions become cash"], answer: 1, feedback: "Twelve weeks is a minimum commitment, not an expiry or renewal point." },
      { q: "A client misses a session because of travel. What is your first instinct?", options: ["Promise a cash refund", "Rebook or spread spare sessions to preserve consistency", "End the client relationship", "Call it a gym-owned session"], answer: 1, feedback: "Spares are not cash refunds. Rebooking and consistency come first." }
    ],
    "trainer-portal": [
      { q: "A Portal value for one client is clearly wrong. What should you do?", options: ["Work around it using another client's record", "Use the bug button with the client, page, value, and expected result", "Wait for payroll to discover it", "Change the value by guessing"], answer: 1, feedback: "Report exact Portal mismatches from the page instead of inventing or bypassing data." },
      { q: "The Portal shows a red notification bar on the device you use. What should you do?", options: ["Enable push notifications", "Clear the client book", "Ignore it until a booking is missed", "Switch to a personal social account"], answer: 0, feedback: "Booking, measurement, and reminder pings depend on notifications being enabled." },
      { q: "You need normal one-to-one client chat, not the required weekly accountability touchpoint. Where do you go?", options: ["JF Coach Messages", "Portal Updates", "JF Notes comments", "Member Names"], answer: 0, feedback: "JF Coach owns live client chat. The Portal Messages tab owns the required weekly accountability workflow." }
    ],
    "program-builder": [
      { q: "A Kickstart client cannot perform part of the standard plan because of a restriction. What do you build?", options: ["An Ongoing program with no Kickstart framing", "Kickstart Custom that respects the restriction", "The unchanged standard plan", "A plan based only on equipment availability"], answer: 1, feedback: "Kickstart Custom preserves the pathway while adapting exercises for a real restriction." },
      { q: "A client trains five days but requested only one or two programs and a glute focus. What should guide the build?", options: ["The automatic five-workout template only", "Both program-count and training-focus preferences", "The trainer's favourite split", "The client's pay tier"], answer: 1, feedback: "Review both intake preferences and adjust the proposed plan before publishing." },
      { q: "You are about to publish and the destination does not clearly say JF Coach. What should you do?", options: ["Publish and check later", "Stop and report the Portal issue", "Create a duplicate client", "Use another trainer's program"], answer: 1, feedback: "Confirm the correct client, dates, and JF Coach destination before publishing." }
    ],
    "jf-notes": [
      { q: "A notification opens a client task. What information should you read before acting?", options: ["Only the task title", "The client history and visible comment thread", "A separate account you create", "Only the most recent workout"], answer: 1, feedback: "JF Notes holds the deal history, comments, and routed task context needed for the next decision." },
      { q: "After a free session, where should you record the structured outcome?", options: ["Session Notes so it can thread to the JF Notes deal", "A private phone note", "The workout tracker", "A payroll timesheet"], answer: 0, feedback: "Session Notes records the outcome. JF Notes is the card, comments, and task system that receives the result." },
      { q: "Which note best supports a handoff?", options: ["Good session", "Client liked it", "Client said knee felt fine, prefers mornings, Foundation Call booked Tuesday", "Follow up sometime"], answer: 2, feedback: "Useful notes capture the outcome, client words, preferences, and exact next action." }
    ],
    "retention-tab": [
      { q: "A client's program shows Overdue while they remain active. What does that call for?", options: ["Wait for the client to request a change", "Refresh the program", "Keep using the expired plan until the next quarterly review", "Treat the overdue label as an attendance issue"], answer: 1, feedback: "Overdue means the main program end date passed while the client remains active." },
      { q: "One check-in dot is missing, but the rest are still loading. What should you do?", options: ["Assume the client is disengaged", "Wait for loading and judge the trend", "Message the whole client book", "Remove the habit"], answer: 1, feedback: "Use the loaded pattern and underlying details rather than one isolated signal." },
      { q: "A client is returning from holiday with no next appointment. What is the useful retention action?", options: ["Leave the return undefined", "Rebook a clear next touchpoint", "Promise a pause", "Wait for a cancellation request"], answer: 1, feedback: "A clear next appointment protects continuity and reduces drift." }
    ],
    "accountability-messages": [
      { q: "You spoke in person about the client's habit and agreed a next action. How can this count for the weekly touchpoint?", options: ["Select Done Outside and document the contact", "Mark it complete without a note", "Send a duplicate generic message", "Use a brand announcement"], answer: 0, feedback: "Done Outside is for a real documented touchpoint completed through another channel and awaits approval." },
      { q: "A client's weekly card is already green and locked. What should you do?", options: ["Send another required message immediately", "Wait for the next weekly cycle while using normal chat as needed", "Clear the status", "Mark every other client Done Outside"], answer: 1, feedback: "One qualifying message completes the required cycle for 7 days. Normal client conversation can still continue in JF Coach." },
      { q: "A client missed meals, steps, and a workout. What makes the accountability message useful?", options: ["List every failure", "Choose one priority action and connect it to real context", "Send the same warning to all clients", "Avoid mentioning any next step"], answer: 1, feedback: "Personalise the message, recognise a real signal, and give one manageable next action." }
    ],
    "booking-links-ipad": [
      { q: "An ongoing client wants only next Tuesday moved. Which scope do you use?", options: ["Move this appointment only", "Move this and all future sessions", "Cancel the full recurring series", "Send it to the VA as a Kickstart change"], answer: 0, feedback: "Choose the smallest correct scope. One occurrence should not alter the rest of the series." },
      { q: "An ongoing client's permanent weekly time changes from Tuesday to Thursday. What must you verify after saving?", options: ["Only the selected appointment", "The changed appointment and the next future occurrence", "The client's Health Score", "The free-session outcome"], answer: 1, feedback: "Use this and following, then confirm the intended future series moved while earlier history stayed unchanged." },
      { q: "A recurring booking reports that one clashing date was skipped. What should you do?", options: ["Assume the full series exists", "Review and resolve the skipped date", "Create a second full series", "Remove every unaffected appointment"], answer: 1, feedback: "Read the booking result and resolve any skipped clash rather than assuming every occurrence was created." },
      { q: "A client wants one recurring series stopped from next month onward. Which action fits?", options: ["Cancel current and future from the first unwanted occurrence", "Cancel only the first unwanted occurrence", "Edit the original appointment that started the series", "Leave the series active until payroll flags it"], answer: 0, feedback: "Cancel current and future when the selected occurrence and the rest of that series must stop." },
      { q: "You discover an incorrect past appointment. What does the trainer flow allow?", options: ["Delete it because all past appointments are editable", "Do not change it through the trainer flow, report the exact issue", "Move it into this week", "Replace it with a spare note only"], answer: 1, feedback: "Treat historical appointments as read-only and report the exact client, date, visible result, and expected result to management." }
    ],
    "jf-app-health-score": [
      { q: "You tap a reaction on a client's activity. How should you think about it?", options: ["It is private trainer-only data", "It sends a real chat message to the client", "It edits the workout result", "It completes payroll"], answer: 1, feedback: "Activity reactions reach the client as real messages, so choose them purposefully." },
      { q: "A schedule-only person has little client history. What should you do?", options: ["Invent a history from similar clients", "Confirm their stage and use the correct VA or management route", "Treat them as a full ongoing client", "Add them to My Training"], answer: 1, feedback: "Limited data can be legitimate for a schedule-only person. Confirm the stage instead of filling gaps." },
      { q: "You need to inspect exactly what a client can see without notifying them. What do you use?", options: ["Open app from the assigned client profile", "My Training", "A new client account", "Portal Updates"], answer: 0, feedback: "Open app shows the exact client experience while keeping trainer and self-training identities separate." }
    ],
    "support-client-jf-app": [
      { q: "A prefilled workout row shows last week's weight. What should you record today?", options: ["Accept it as completed", "The reps and kilograms actually completed today", "Only a screenshot", "The planned value even if the client stopped early"], answer: 1, feedback: "History is a starting point, not proof of today's set. Record the real result." },
      { q: "You finish entering sets and leave the tracking screen without the rating step. Is the flow complete?", options: ["Yes, because the sets are visible", "No, save through RPE and rating, then confirm activity", "Yes, if the trainer remembers it", "No, but a Portal note replaces the save"], answer: 1, feedback: "The workout is complete only after the final save and confirmation under the correct client and date." },
      { q: "JF Coach opens with the wrong identity. What is the approved recovery in this module?", options: ["Reinstall the app", "Open it from the Trainer Portal. If it is still wrong, stop and tell management. Do not reinstall.", "Use the wrong account temporarily", "Create a replacement client"], answer: 1, feedback: "Sign in through the Trainer Portal. Do not reinstall, and do not reset the app unless management says to." }
    ],
    "daily-ops-toolkit": [
      { q: "A free-session client does not show. What should happen before the next person acts?", options: ["Record the one accurate No show outcome and required status", "Send an informal message but leave the outcome blank", "Move the booking yourself and record it as attended", "Wait for the VA to infer the result from the calendar"], answer: 0, feedback: "The structured outcome starts the approved recovery flow and gives the team usable context." },
      { q: "A Portal page is wrong, while JF Coach itself is working normally. Where do you report it?", options: ["The Portal bug button on the affected page", "A client chat thread", "The payroll calendar", "A personal social message"], answer: 0, feedback: "Portal issues use the in-page bug flow. JF Coach app issues go directly to management." },
      { q: "The gym iPad blocks the embedded Foundation Call calendar. What is the supported fallback?", options: ["Use the open-on-phone fallback", "Create a JF Coach recurring session", "Use JFCal despite the label risk", "Skip the handoff"], answer: 0, feedback: "Use the native Foundation Call route and its phone fallback when the gym filter blocks the embed." }
    ],
    "free-session-to-kickstart": [
      { q: "Capstone: A client completes the free session, buys Kickstart, and chooses Tuesday for session one. What is the complete next sequence?", options: ["Take payment, then decide the outcome later", "Book Tuesday, take approved payment, record Kickstart purchased with payment and next booking, then confirm the handoff", "Add an ongoing recurring series and message payroll", "Send the client away, then ask the VA what happened"], answer: 1, feedback: "A safe close preserves the booking, payment result, one accurate outcome, required fields, client words, and the next-person handoff." },
      { q: "A client leaves without buying but agrees to a Foundation Call. What must the record include?", options: ["Only high intent", "Booked a call, the correct call type and time, objections, goals, injuries, and next action", "Kickstart purchased because a call exists", "No outcome until the call occurs"], answer: 1, feedback: "Choose the real outcome and complete its branch so the follow-up does not depend on memory." },
      { q: "A free-session client no-shows and asks you directly to reschedule. What do you do?", options: ["Move it yourself in ongoing Schedule", "Record the No show outcome and let the VA manage scheduling", "Delete the appointment and client", "Mark Kickstart purchased to preserve the lead"], answer: 1, feedback: "Record the accurate outcome. Free-session rescheduling belongs to the VA." },
      { q: "The client mentions knee pain and declines the offer. Which note is most useful?", options: ["Not interested", "Client declined", "Not interested, injury or health objection, client's words about knee pain, and agreed next action", "No note because there was no sale"], answer: 2, feedback: "The outcome branch and free text must preserve the real objection, client words, and next action." }
    ],
    "selling-the-kickstart": [
      { q: "During the warm-up, a client reports new sharp pain and uncertainty about training. What should happen before any close?", options: ["Continue the sales script to maintain momentum", "Prioritise safety and understand whether the Kickstart is appropriate", "Offer a discount immediately", "Manufacture urgency around the intake"], answer: 1, feedback: "The offer must fit the person. Honest diagnosis and safety come before pressure or script completion." },
      { q: "A suitable client says yes to Kickstart. Which order makes the commitment concrete?", options: ["Take payment, then discuss a date later", "Lock all three sessions, take payment on the agreed chip, then confirm the handoff", "Record the sale before either booking or payment", "Promise the offer will remain forever"], answer: 1, feedback: "Lock all three sessions before payment. Then use Full $99.99, an agreed $69.99, or Split." },
      { q: "Historical materials disagree on the Kickstart bonus amount. What should you do?", options: ["Use the amount from the newest-looking screenshot", "Confirm the live amount with Jamie or Gabrielle", "Use the amount another trainer remembers", "Calculate it from the client's package price"], answer: 1, feedback: "The cumulative payment threshold is documented, but the bonus amount is not resolved in current source material. Confirm it before relying on or quoting it." },
      { q: "The live process shows no intake deadline. What urgency may you use?", options: ["Invent a deadline to help them decide", "Only the real goal urgency and current live offer", "Say the price doubles tonight", "Claim the last place is available"], answer: 1, feedback: "Use real relevance and actual intake timing. Never manufacture scarcity." }
    ],
    "objection-handling": [
      { q: "A client says, 'I need to think about it.' What is the first useful move?", options: ["Offer the largest discount", "Empathise and clarify what information is missing", "End the conversation immediately", "Tell them thinking is not allowed"], answer: 1, feedback: "Use empathy, isolate the real barrier, then address that barrier without shame." },
      { q: "A client wants to start but payday is next week. What is the appropriate path?", options: ["Pretend cost is not the issue", "Confirm payday, use the approved delayed-payment follow-up, and record it", "Mark payment complete now", "Promise an unapproved free week"], answer: 1, feedback: "Treat the real barrier honestly and use the approved delayed-payment process." },
      { q: "They want to start but cannot pay $99.99 today. What is allowed?", options: ["Offer $33.33 as the standard rescue", "Use Full $99.99, an agreed $69.99, or Split. Otherwise book payday. Do not invent a price.", "Promise the Kickstart stays open forever", "Mark the payment complete now"], answer: 1, feedback: "Only the chips on the payment screen are real. $33.33 is not a chip." }
    ],
    "21-day-onboarding": [
      { q: "A week-one client is overwhelmed by nutrition tracking. What should you do?", options: ["Add steps and two more habits", "Choose the simplest approved meal-tracking action", "Skip nutrition for all three weeks", "Give a complete nutrition lecture"], answer: 1, feedback: "Build one layer at a time and reduce the action until it is realistic." },
      { q: "In week three, what proves the independence goal occurred?", options: ["The client says they might train alone", "A real solo workout is logged through the full JF Coach save flow", "A new program is drafted", "The Strategy Session is mentioned"], answer: 1, feedback: "The client completes and logs a solo workout, including the RPE and rating save step." },
      { q: "The final Kickstart session ends with no Strategy Session booked. What should happen?", options: ["Wait until the client contacts Gabrielle", "Use the mandatory value script and book the handoff", "Create an ongoing package yourself", "Describe Kickstart as finished and closed"], answer: 1, feedback: "Strategy booking is part of graduation and the trainer records the Post-KSP context." }
    ],
    "count-cue-encourage": [
      { q: "A beginner squat shows knees moving in, chest dropping, and heels lifting. What should you do first?", options: ["Give all three corrections at once", "Choose one clear priority action while continuing to count and observe", "Stop counting and give an anatomy lecture", "Praise the set without changing anything"], answer: 1, feedback: "Give one actionable cue at a time while preserving the rep count, observation, and session awareness." },
      { q: "A client looks confident before a new exercise. What should you do?", options: ["Skip the demonstration", "Demonstrate before their first attempt", "Wait for a mistake", "Ask another client to demonstrate"], answer: 1, feedback: "Always demonstrate a new exercise before the first attempt, even when the client appears confident." },
      { q: "Which encouragement is most useful near the end of a hard set?", options: ["Good job, repeated every rep", "Two more, Sarah, strong control", "A long explanation of the program", "Silence while looking away"], answer: 1, feedback: "Useful encouragement is short, personal, specific, and blended with a clear finish line." }
    ],
    "running-great-sessions": [
      { q: "A client reports sharp pain during an exercise. What do you do?", options: ["Reduce the load but finish the set", "Stop the movement and choose a safe next action", "Tell them pain is normal", "Record the planned reps as complete"], answer: 1, feedback: "Pain and safety signals override the planned set. Stay within scope and do not push through." },
      { q: "A machine is busy during a session. What is the best adaptation?", options: ["Leave the client waiting alone", "Move to the next superset or use the same movement pattern, then record the substitution", "Choose an unrelated exercise without recording it", "Cancel the session"], answer: 1, feedback: "Preserve the training goal, supervision, and useful workout history." },
      { q: "Two clients are training together. Which pairing should you avoid?", options: ["Nearby low-risk supersets", "A barbell squat for one while the other bench presses", "Exercises close enough to supervise", "Separate tracking for each client"], answer: 1, feedback: "Do not divide attention across two high-risk lifts. Keep both people close, moving, and separately tracked." },
      { q: "A hard final set of RDLs approaches failure. What should guide you?", options: ["Push to failure for progress", "Stop with safe reps in reserve and protect spinal position", "Add weight immediately", "Use the stopwatch only"], answer: 1, feedback: "Squats and RDLs should not be trained to failure. Technique and safe fatigue management come first." }
    ],
    "retention-mastery": [
      { q: "A client says, 'My 12 weeks are nearly finished.' How should you respond?", options: ["Confirm training expires", "Talk about the next goal and explain the minimum moves naturally to Flexi", "Offer another free session", "Ask them to renew the same term immediately"], answer: 1, feedback: "Use future-based language. The minimum commitment is not an ending." },
      { q: "A client moves suburbs and the current arrangement no longer works. What is the retention-minded action?", options: ["Let the relationship end without discussion", "Explore a Jamie Fitness network referral and transfer useful context", "Share their details informally with any trainer", "Promise a refund"], answer: 1, feedback: "Protect continuity through an approved network handoff with goals, progress, and notes." },
      { q: "Who runs the Quarterly Game Plan?", options: ["The trainer runs the full deck", "Gabrielle or Jamie, with trainer context and follow-through", "The VA without trainer input", "The client alone"], answer: 1, feedback: "The trainer supplies useful context and acts on the handoff, but Gabrielle or Jamie runs the session." }
    ],
    "quarterly-game-plan-playbook": [
      { q: "Before a Game Plan, what is the trainer's most useful contribution?", options: ["A vague statement that training is fine", "Specific progress, barriers, preferences, and the next opportunity", "A new package promise", "Only the client's phone number"], answer: 1, feedback: "The operator needs real trainer context to review the quarter and prescribe the next block." },
      { q: "There is no valid weigh-in or scan for the comparison stage. What should happen?", options: ["Invent a baseline", "Skip that stage and use valid evidence", "Cancel the whole Game Plan", "Use another client's figures"], answer: 1, feedback: "The playbook explicitly skips the numbers comparison when no valid data exists." },
      { q: "After the Game Plan sets a new goal and program prescription, what does the trainer own?", options: ["Ignoring it until the next quarter", "Using the new focus in sessions and messages", "Changing the agreed goal privately", "Re-running the deck"], answer: 1, feedback: "The trainer turns the handoff into the next 12 weeks of training support." }
    ],
    "policy-professionalism": [
      { q: "An ongoing client cancels tonight's session 3 hours beforehand and does not reschedule. What do you do?", options: ["Remove it and create a spare", "Leave it in the calendar, explain the forfeiture, and keep the record accurate", "Move it to next week automatically", "Promise a refund"], answer: 1, feedback: "A late-cancelled forfeited session stays in the calendar and remains paid." },
      { q: "A client gives 10 hours notice for a 7am session. Which rule applies?", options: ["Ten hours always satisfies the policy", "Morning sessions require notice by 6pm the night before", "All morning sessions are automatically spared", "Only the VA decides after the session"], answer: 1, feedback: "For sessions before about 11am, notice is due by 6pm the previous night." },
      { q: "You choose to be nice and move a late-cancelled session. What must happen to the original?", options: ["Leave it in so the client forfeits and trains later", "Remove the original appointment so it is not also paid and forfeited", "Duplicate it as a spare", "Change only the JF Notes text"], answer: 1, feedback: "A reschedule comes out of the original slot. Do not create double pay or double use." },
      { q: "A client asks to pause and wants Gabrielle's personal number. What do you do?", options: ["Give the number to speed it up", "Direct the client to email the team, log their reason, and alert Gabrielle", "Promise the pause yourself", "Remove all appointments immediately without confirmation"], answer: 1, feedback: "Cancellation and pause requests use the formal email ticket process. Never give personal numbers or promise the outcome." },
      { q: "A spare session is created and later used. What documentation is required?", options: ["One note only when it is created", "JF Notes entries when the spare is created and when it is used", "No note if the calendar is correct", "A personal text message"], answer: 1, feedback: "Every spare created and every spare used must be recorded in JF Notes." }
    ],
    "pay-tiers-kpis": [
      { q: "A trainer has many clients, but few weekly ongoing hours. What determines the pay tier?", options: ["Total names assigned to the trainer", "Ongoing hours", "Free-session bookings before attendance", "All calendar hours including gaps"], answer: 1, feedback: "The current tier framework is based on ongoing hours, not the number of names in the book." },
      { q: "Free-session attendance is weak while close rate among attendees is healthy. Where should improvement focus?", options: ["Booking quality, reminders, and attendance recovery", "The ongoing package price", "Program refresh timing", "The trainer pay band"], answer: 0, feedback: "Different KPIs diagnose different funnel stages. Low show rate points before the close." },
    ],
    "payroll-rules": [
      { q: "Friday capstone: One client completed Monday, one forfeited a late cancel Tuesday, one moved Wednesday to next week, and one paused client still has Thursday booked. What should the calendar show before close?", options: ["All four appointments", "Monday and Tuesday only", "Monday, Wednesday, and Thursday", "Tuesday and Thursday only"], answer: 1, feedback: "Completed and forfeited sessions stay. The rescheduled original comes out, and paused clients must be absent." },
      { q: "You work 30 minutes at 8am, 2 hours at noon, and 1 hour at 7pm. Which concern should you recognise?", options: ["The isolated short session simply removes all pay", "Three separate blocks breach the two-block rule and create a scattered day", "The day automatically becomes a public holiday", "The 30-minute session must be deleted"], answer: 1, feedback: "An isolated short engagement can pay a minimum hour, but the day may contain at most two blocks and should be built back-to-back." },
      { q: "You are booked 7am to 12:30pm with no gap. What change is required?", options: ["None, because the paid 20-minute break covers it", "Add a 30 to 60 minute unpaid meal break before the fifth hour", "Split it into three work blocks", "Move the first session outside ordinary hours"], answer: 1, feedback: "More than 3 hours also earns an automatic paid 20-minute break, but 5 or more straight hours still requires an unpaid meal break before hour five." },
      { q: "You finish Friday at 9pm and plan Saturday from 6am to 6:30pm with 9 working hours in two blocks. What must change?", options: ["Nothing, because Saturday starts a new pay week", "The 6am start breaches the 10-hour rest rule, and the full span exceeds 12 hours", "Only the weekend rate needs manual entry", "Add a third block to shorten the others"], answer: 1, feedback: "The new pay week does not remove shift rules. After 9pm, the earliest start is 7am, and the day must fit inside a 12-hour span with no more than two blocks and 10 work hours." },
      { q: "Which weekly pay items are added automatically rather than entered as appointments by the trainer?", options: ["Weekly admin, team meetings, 1:1s, qualifying Kickstart bonus, paid break, split allowance, and public-holiday minimum", "Only completed client sessions", "Every personal message and Portal login", "Travel time and any empty calendar gap"], answer: 0, feedback: "The system automatically applies the listed admin hours and rule-based additions. Public holiday work has a 4-hour minimum, and weekends and public holidays use the higher rate." }
    ],
    "working-with-the-va": [
      { q: "A Kickstart client asks you to move tomorrow's session. What do you do?", options: ["Move it in the ongoing-client flow", "Send the scheduling change and context to the VA", "Ask another trainer to take over privately", "Leave the request undocumented"], answer: 1, feedback: "The VA manages Kickstart scheduling changes. The trainer supplies the relevant context." },
      { q: "An ongoing client has stopped responding and still has appointments booked. What is your role?", options: ["Remove every appointment immediately", "Alert the VA straight away, keep the calendar accurate, and follow team direction", "Send repeated generic messages for several weeks", "Promise a pause"], answer: 1, feedback: "You own ongoing appointment accuracy, but difficult or unresponsive client risk is escalated immediately." },
      { q: "A free-session client no-shows. What should the trainer record?", options: ["The accurate no-show outcome for the VA and management", "An ongoing cancellation", "A completed workout", "A private reminder only"], answer: 0, feedback: "The outcome record gives the VA and management the facts needed for the next action." }
    ],
    "incident-reporting": [
      { q: "A client becomes faint beside a machine that has just jammed, and your next session starts in 5 minutes. What is the correct order?", options: ["Start the next session, then report the machine", "Stop, make the person and area safe, stay with them, escalate care, reschedule the next client, then report", "Write the report before checking the client", "Move the client aside and continue using the machine"], answer: 1, feedback: "Immediate care and area safety come first. Never leave an unwell client to protect the next booking." },
      { q: "The client's condition worsens while you are staying with them. What should you do?", options: ["Wait for Gabrielle to reply before acting", "Call 000 and follow your first aid responsibilities", "Ask the client to drive home", "Finish the report first"], answer: 1, feedback: "Call 000 for a serious or worsening condition. Management notification does not replace emergency action." },
      { q: "What belongs in the same-day incident report about the faulty machine?", options: ["A guess about who caused the fault", "The sequence, equipment, observations, actions, condition, witnesses, and fault report", "Only the client's opinion", "A one-line statement that something happened"], answer: 1, feedback: "Record objective, specific facts, your response, the person's condition, witnesses, and follow-up." },
      { q: "What follow-up is required after the immediate incident is handled?", options: ["No contact unless the client complains", "Check in the next day and complete the stated follow-up actions", "Delete the appointment history", "Post about the event to warn other clients"], answer: 1, feedback: "File the report the same day and check on the person the next day." }
    ]
  };

  var data = window.JF_HANDBOOK_CONTENT;
  data.parts.forEach(function (part) {
    part.modules.forEach(function (module) {
      module.blocks = module.blocks.filter(function (block) { return block.type !== "quiz"; });
      if (quizzes[module.slug]) module.blocks.push({ type: "quiz", questions: quizzes[module.slug] });
    });
  });

  window.JF_HANDBOOK_QUIZZES = quizzes;
}());
